export { default as Home } from './Home'
export { default as Order } from './Order'
export { default as Cart } from './Cart'
export { default as NicheProducts } from './NicheProducts'
export { default as ProductDetail } from './ProductDetail'
